apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitas-downloaders-youtube
  namespace: sitas
spec:
  selector:
    matchLabels:
      app: sitas-downloaders-youtube
  template:
    metadata:
      labels:
        app: sitas-downloaders-youtube
    spec:
      containers:
        - name: sitas-downloaders-youtube
          image: oscarvicente/sitas-downloaders-youtube-prod
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
          env: 
            - name: AZURE_SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-youtube-secret
                  key: AZURE_SERVICE_BUS_CONNECTION_STRING
            - name: AZURE_SERVICE_BUS_DOWNLOAD_REQUEST_QUEUE
              value: download-request-prod
            - name: AZURE_SERVICE_BUS_DOWNLOAD_REQUEST_YOUTUBE_QUEUE
              value: download-request-youtube-prod
            - name: AZURE_SERVICE_BUS_DOWNLOAD_COMPLETED_QUEUE
              value: download-completed-prod
            - name: MINIO_INTERNAL_ENDPOINT
              value: oscarvx00.ddns.net
            - name: MINIO_INTERNAL_PORT
              value: "10000"
            - name: MINIO_INTERNAL_USER
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-youtube-secret
                  key: MINIO_INTERNAL_USER
            - name: MINIO_INTERNAL_PASS
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-youtube-secret
                  key: MINIO_INTERNAL_PASS
            - name: MINIO_INTERNAL_BUCKET
              value: internal-storage-prod
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-youtube-secret
                  key: YOUTUBE_API_KEY